---
galaxy_info:
  author: "Ramon de la Fuente"
  description: Deploy_helper module for building (Capistrano like) deploy roles
  company: Future500
  license: LGPL
  min_ansible_version: 1.4
  categories:
    - web
  platforms:
    - name: Debian
      versions:
        - all
dependencies: []
