- hosts: lbservers:dbservers
  #sudo: true
  tasks:
    - name: update openssh
      yum: name=openssh state=latest

- hosts: appservers
  #sudo: true
  tasks:
    - name: update openssh
      apt: name=openssh-server state=latest
