---
# file: tasks/main.yml
# Top-level installer for Node.js.
#
# @see https://github.com/nodesource/distributions
#


- name: set role variables, if necessary
  include: set-role-variables.yml


- name: delegate to APT system for installation
  include: use-apt.yml
  when: ansible_pkg_mgr == "apt"

- name: delegate to YUM system for installation
  include: use-yum.yml
  when: ansible_pkg_mgr == "yum"